### ISSUE TITLE
'verify_token' should be 'verifyToken'

### ISSUE THREAD

**Issue by davydelbeke** [FutureActivities/Craft3-REST-API#1]
I was never able to verify my token worked because the code was checking wether verify_token parameter existed. But it should've been verifyToken.

Changing it, made it work like a charm! :)

https://github.com/FutureActivities/Craft3-REST-API/blob/490f23f4cae2fb28ab9ad27e95b7831ad68df89e/src/controllers/v1/UserController.php#L151

**Comment by nzimelimited** [comment]
Thanks, this has now been updated at long last: https://github.com/FutureActivities/Craft3-REST-API/commit/70710cf50bd343d92c1244121b8224dbe368e691
